### ISSUE TITLE
Tabs show up below address bar but above bookmarks bar

### ISSUE THREAD

**Issue by tojaroslaw** [HKayn/antonio-lucio#1]
Hi there HKayn,

I'm really happy there's another sane person out there who knows that tabs on bottom is the only way to go.  I really like what you are doing, but I am currently experiencing an issue where the bookmarks bar still sits below the tab bar, getting between tab an the page.  I would love it if this worked with the bookmark bar on.

Thanks!

**Comment by HKayn** [comment]
Hi tojaroslaw, thanks for making me aware of this!

I've just released v1.1.0, which addresses your issue: https://github.com/HKayn/antonio-lucio/releases/tag/v1.1.0

**Comment by tojaroslaw** [comment]
Thanks so much!
